<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DocumentCategorySeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            // === KARIR & PEKERJAAN ===
            [
                'slug' => 'cv-profesional',
                'name' => 'CV Profesional',
                'group' => 'Karir & Pekerjaan',
                'icon' => '👤',
                'description' => 'Curriculum Vitae profesional untuk melamar kerja',
                'color' => '#DC2626',
                'templates' => json_encode(['Modern Clean', 'ATS Friendly']),
                'fields' => json_encode(['nama_lengkap','foto','email','telepon','alamat','ringkasan','pengalaman_kerja','pendidikan','keahlian','sertifikasi','bahasa','media_sosial']),
            ],
            [
                'slug' => 'cv-kreatif',
                'name' => 'CV Kreatif',
                'group' => 'Karir & Pekerjaan',
                'icon' => '🎨',
                'description' => 'CV dengan desain kreatif dan visual menarik',
                'color' => '#7C3AED',
                'templates' => json_encode(['Colorful Bold', 'Infographic Style']),
                'fields' => json_encode(['nama_lengkap','foto','tagline','email','telepon','keahlian','portofolio','pengalaman','pendidikan','hobi','warna_tema']),
            ],
            [
                'slug' => 'cv-ats',
                'name' => 'CV ATS',
                'group' => 'Karir & Pekerjaan',
                'icon' => '🤖',
                'description' => 'CV yang lolos sistem ATS (Applicant Tracking System)',
                'color' => '#059669',
                'templates' => json_encode(['ATS Classic', 'ATS Minimal']),
                'fields' => json_encode(['nama_lengkap','email','telepon','linkedin','ringkasan_profesional','pengalaman_kerja','pendidikan','keahlian_teknis','sertifikasi','kata_kunci']),
            ],
            [
                'slug' => 'surat-lamaran',
                'name' => 'Surat Lamaran Kerja',
                'group' => 'Karir & Pekerjaan',
                'icon' => '✉️',
                'description' => 'Surat lamaran pekerjaan formal',
                'color' => '#2563EB',
                'templates' => json_encode(['Formal Classic', 'Modern Minimalis']),
                'fields' => json_encode(['nama_pelamar','alamat','email','telepon','tanggal','nama_perusahaan','alamat_perusahaan','posisi_dilamar','asal_info_lowongan','isi_lamaran','pengalaman_relevan']),
            ],
            [
                'slug' => 'surat-resign',
                'name' => 'Surat Pengunduran Diri',
                'group' => 'Karir & Pekerjaan',
                'icon' => '🚪',
                'description' => 'Surat pengunduran diri (resign) dari pekerjaan',
                'color' => '#DC2626',
                'templates' => json_encode(['Formal Resign', 'Friendly Farewell']),
                'fields' => json_encode(['nama','jabatan','departemen','nama_atasan','perusahaan','tanggal_surat','tanggal_efektif','alasan_resign','ucapan_terima_kasih']),
            ],
            [
                'slug' => 'surat-referensi-kerja',
                'name' => 'Surat Referensi Kerja',
                'group' => 'Karir & Pekerjaan',
                'icon' => '📋',
                'description' => 'Surat rekomendasi atau referensi dari atasan/rekan',
                'color' => '#0891B2',
                'templates' => json_encode(['Reference Professional', 'Character Reference']),
                'fields' => json_encode(['nama_pemberi_referensi','jabatan_pemberi','perusahaan','nama_yang_direferensi','jabatan_yang_direferensi','periode_kerja','deskripsi_kinerja','rekomendasi','kontak_pemberi']),
            ],
            [
                'slug' => 'surat-keterangan-kerja',
                'name' => 'Surat Keterangan Kerja',
                'group' => 'Karir & Pekerjaan',
                'icon' => '🏢',
                'description' => 'Surat keterangan masih aktif bekerja di perusahaan',
                'color' => '#0D9488',
                'templates' => json_encode(['Resmi Perusahaan', 'Bilingual']),
                'fields' => json_encode(['nama_karyawan','jabatan','departemen','tanggal_masuk','status_karyawan','nama_perusahaan','alamat_perusahaan','nama_hr','jabatan_hr','keperluan']),
            ],
            [
                'slug' => 'surat-pengalaman-kerja',
                'name' => 'Surat Pengalaman Kerja',
                'group' => 'Karir & Pekerjaan',
                'icon' => '📄',
                'description' => 'Surat keterangan pengalaman kerja setelah resign',
                'color' => '#7C3AED',
                'templates' => json_encode(['Paklaring Resmi', 'Experience Letter']),
                'fields' => json_encode(['nama_karyawan','jabatan','departemen','tanggal_masuk','tanggal_keluar','deskripsi_tugas','penilaian_kinerja','nama_perusahaan','ttd_hrd']),
            ],

            // === BISNIS & KEUANGAN ===
            [
                'slug' => 'invoice',
                'name' => 'Invoice / Faktur',
                'group' => 'Bisnis & Keuangan',
                'icon' => '🧾',
                'description' => 'Tagihan profesional untuk klien atau pelanggan',
                'color' => '#D97706',
                'templates' => json_encode(['Invoice Minimalis', 'Invoice Korporat']),
                'fields' => json_encode(['nama_bisnis','logo','alamat_bisnis','email_bisnis','nomor_invoice','tanggal_invoice','jatuh_tempo','nama_klien','alamat_klien','item_jasa','subtotal','pajak','diskon','total','catatan','rekening_bank']),
            ],
            [
                'slug' => 'kwitansi',
                'name' => 'Kwitansi Pembayaran',
                'group' => 'Bisnis & Keuangan',
                'icon' => '💳',
                'description' => 'Bukti penerimaan pembayaran',
                'color' => '#16A34A',
                'templates' => json_encode(['Kwitansi Formal', 'Kwitansi Simple']),
                'fields' => json_encode(['nomor_kwitansi','tanggal','nama_pembayar','alamat_pembayar','jumlah','terbilang','untuk_pembayaran','nama_penerima','jabatan_penerima']),
            ],
            [
                'slug' => 'penawaran-harga',
                'name' => 'Surat Penawaran Harga',
                'group' => 'Bisnis & Keuangan',
                'icon' => '💼',
                'description' => 'Proposal penawaran harga produk atau jasa',
                'color' => '#2563EB',
                'templates' => json_encode(['Quotation Formal', 'Proposal Modern']),
                'fields' => json_encode(['nama_perusahaan','logo','nama_klien','tanggal','berlaku_hingga','daftar_produk_jasa','ketentuan','syarat_pembayaran','catatan','ttd']),
            ],
            [
                'slug' => 'purchase-order',
                'name' => 'Purchase Order (PO)',
                'group' => 'Bisnis & Keuangan',
                'icon' => '📦',
                'description' => 'Surat pesanan pembelian resmi',
                'color' => '#0891B2',
                'templates' => json_encode(['PO Standard', 'PO Detail']),
                'fields' => json_encode(['nomor_po','tanggal_po','nama_pembeli','alamat_pembeli','nama_vendor','alamat_vendor','daftar_item','ketentuan_pengiriman','syarat_pembayaran','catatan']),
            ],
            [
                'slug' => 'nota-dinas',
                'name' => 'Nota Dinas',
                'group' => 'Bisnis & Keuangan',
                'icon' => '📝',
                'description' => 'Nota dinas internal perusahaan atau instansi',
                'color' => '#7C3AED',
                'templates' => json_encode(['Nota Dinas Formal', 'Memo Internal']),
                'fields' => json_encode(['nomor_nota','tanggal','dari','kepada','perihal','isi_nota','lampiran','ttd']),
            ],
            [
                'slug' => 'proposal-bisnis',
                'name' => 'Proposal Bisnis',
                'group' => 'Bisnis & Keuangan',
                'icon' => '🚀',
                'description' => 'Proposal rencana bisnis atau kerja sama',
                'color' => '#DC2626',
                'templates' => json_encode(['Business Plan', 'Partnership Proposal']),
                'fields' => json_encode(['nama_bisnis','logo','nama_pemilik','deskripsi_bisnis','visi_misi','produk_jasa','target_pasar','analisis_kompetitor','rencana_pemasaran','proyeksi_keuangan','tim','investasi_diperlukan']),
            ],
            [
                'slug' => 'kontrak-kerja',
                'name' => 'Kontrak Kerja',
                'group' => 'Bisnis & Keuangan',
                'icon' => '🤝',
                'description' => 'Perjanjian kontrak antara pekerja dan perusahaan',
                'color' => '#0D9488',
                'templates' => json_encode(['Kontrak PKWT', 'Kontrak Freelance']),
                'fields' => json_encode(['nama_perusahaan','nama_karyawan','posisi','tanggal_mulai','tanggal_berakhir','gaji','tunjangan','jam_kerja','hak_kewajiban','pasal_pasal','ttd_para_pihak']),
            ],
            [
                'slug' => 'mou',
                'name' => 'MOU / Perjanjian Kerjasama',
                'group' => 'Bisnis & Keuangan',
                'icon' => '📜',
                'description' => 'Memorandum of Understanding atau perjanjian kerja sama',
                'color' => '#D97706',
                'templates' => json_encode(['MOU Formal', 'PKS Standard']),
                'fields' => json_encode(['pihak_pertama','pihak_kedua','tujuan_kerjasama','ruang_lingkup','hak_kewajiban_p1','hak_kewajiban_p2','jangka_waktu','penyelesaian_sengketa','ttd_kedua_pihak']),
            ],
            [
                'slug' => 'laporan-keuangan',
                'name' => 'Laporan Keuangan Sederhana',
                'group' => 'Bisnis & Keuangan',
                'icon' => '📊',
                'description' => 'Laporan arus kas atau neraca keuangan sederhana',
                'color' => '#16A34A',
                'templates' => json_encode(['Laporan Bulanan', 'Laporan Tahunan']),
                'fields' => json_encode(['nama_usaha','periode','pendapatan','pengeluaran','laba_rugi','catatan','nama_penyusun']),
            ],

            // === PENDIDIKAN ===
            [
                'slug' => 'surat-izin-siswa',
                'name' => 'Surat Izin Tidak Masuk Sekolah',
                'group' => 'Pendidikan',
                'icon' => '🏫',
                'description' => 'Surat izin tidak hadir untuk siswa/mahasiswa',
                'color' => '#2563EB',
                'templates' => json_encode(['Izin Sakit', 'Izin Keperluan Keluarga']),
                'fields' => json_encode(['nama_orang_tua','nama_siswa','kelas','tanggal_izin','lama_izin','alasan','nama_sekolah','nama_guru_wali']),
            ],
            [
                'slug' => 'surat-rekomendasi-akademik',
                'name' => 'Surat Rekomendasi Akademik',
                'group' => 'Pendidikan',
                'icon' => '🎓',
                'description' => 'Surat rekomendasi dari dosen atau guru untuk beasiswa/studi lanjut',
                'color' => '#7C3AED',
                'templates' => json_encode(['Rekomendasi Beasiswa', 'Rekomendasi S2/S3']),
                'fields' => json_encode(['nama_pemberi_rekomendasi','jabatan','institusi','nama_mahasiswa','program_studi','ipk','prestasi','karakter','rekomendasi_untuk','kontak']),
            ],
            [
                'slug' => 'makalah',
                'name' => 'Cover Makalah / Karya Tulis',
                'group' => 'Pendidikan',
                'icon' => '📚',
                'description' => 'Halaman sampul makalah atau karya tulis ilmiah',
                'color' => '#0891B2',
                'templates' => json_encode(['Cover Sekolah', 'Cover Kampus']),
                'fields' => json_encode(['judul_makalah','logo_institusi','mata_pelajaran','nama_penyusun','nim_nis','kelas','nama_institusi','kota','tahun']),
            ],
            [
                'slug' => 'proposal-penelitian',
                'name' => 'Proposal Penelitian',
                'group' => 'Pendidikan',
                'icon' => '🔬',
                'description' => 'Proposal skripsi, tesis, atau penelitian ilmiah',
                'color' => '#DC2626',
                'templates' => json_encode(['Proposal Skripsi', 'Proposal PKM']),
                'fields' => json_encode(['judul','latar_belakang','rumusan_masalah','tujuan','manfaat','metode','tinjauan_pustaka','jadwal','anggaran','nama_peneliti','dosen_pembimbing']),
            ],
            [
                'slug' => 'surat-pernyataan-mahasiswa',
                'name' => 'Surat Pernyataan Mahasiswa',
                'group' => 'Pendidikan',
                'icon' => '✍️',
                'description' => 'Surat pernyataan orisinalitas, kesanggupan, dll',
                'color' => '#0D9488',
                'templates' => json_encode(['Pernyataan Orisinalitas', 'Pernyataan Kesanggupan']),
                'fields' => json_encode(['nama','nim','program_studi','jurusan','nama_kampus','jenis_pernyataan','isi_pernyataan','kota','tanggal','materai']),
            ],
            [
                'slug' => 'biodata-siswa',
                'name' => 'Biodata Siswa / Mahasiswa',
                'group' => 'Pendidikan',
                'icon' => '📋',
                'description' => 'Formulir biodata untuk keperluan sekolah atau kampus',
                'color' => '#D97706',
                'templates' => json_encode(['Biodata Sekolah', 'Biodata Mahasiswa']),
                'fields' => json_encode(['nama_lengkap','foto','tempat_lahir','tanggal_lahir','agama','alamat','nama_ayah','nama_ibu','pekerjaan_ortu','nomor_hp','email','prestasi','hobi']),
            ],

            // === LEGAL & ADMINISTRATIF ===
            [
                'slug' => 'surat-kuasa',
                'name' => 'Surat Kuasa',
                'group' => 'Legal & Administratif',
                'icon' => '⚖️',
                'description' => 'Surat pelimpahan wewenang atau kuasa kepada seseorang',
                'color' => '#DC2626',
                'templates' => json_encode(['Surat Kuasa Umum', 'Surat Kuasa Khusus']),
                'fields' => json_encode(['nama_pemberi','nik_pemberi','alamat_pemberi','nama_penerima','nik_penerima','alamat_penerima','keperluan_kuasa','batas_berlaku','kota','tanggal','materai']),
            ],
            [
                'slug' => 'surat-pernyataan-umum',
                'name' => 'Surat Pernyataan',
                'group' => 'Legal & Administratif',
                'icon' => '📃',
                'description' => 'Surat pernyataan untuk berbagai keperluan resmi',
                'color' => '#2563EB',
                'templates' => json_encode(['Pernyataan Umum', 'Pernyataan Kepemilikan']),
                'fields' => json_encode(['nama','nik','tempat_lahir','tanggal_lahir','alamat','pekerjaan','isi_pernyataan','kota','tanggal','materai']),
            ],
            [
                'slug' => 'surat-domisili',
                'name' => 'Surat Keterangan Domisili',
                'group' => 'Legal & Administratif',
                'icon' => '🏠',
                'description' => 'Surat keterangan tempat tinggal dari RT/RW atau kelurahan',
                'color' => '#0D9488',
                'templates' => json_encode(['Domisili RT/RW', 'Domisili Kelurahan']),
                'fields' => json_encode(['nama','nik','tempat_lahir','tanggal_lahir','agama','pekerjaan','alamat_domisili','rt','rw','kelurahan','kecamatan','kota','keperluan','nama_pejabat']),
            ],
            [
                'slug' => 'surat-kematian',
                'name' => 'Surat Keterangan Kematian',
                'group' => 'Legal & Administratif',
                'icon' => '🕊️',
                'description' => 'Surat keterangan meninggal dunia dari RT/RW atau kelurahan',
                'color' => '#6B7280',
                'templates' => json_encode(['Keterangan RT/RW', 'Format Kelurahan']),
                'fields' => json_encode(['nama_almarhum','nik','tempat_lahir','tanggal_lahir','tanggal_meninggal','tempat_meninggal','penyebab','alamat','nama_pelapor','hubungan_pelapor','nama_pejabat']),
            ],
            [
                'slug' => 'surat-nikah-adat',
                'name' => 'Undangan / Surat Nikah Adat',
                'group' => 'Legal & Administratif',
                'icon' => '💍',
                'description' => 'Undangan pernikahan atau surat keterangan nikah adat',
                'color' => '#BE185D',
                'templates' => json_encode(['Undangan Modern', 'Undangan Islami']),
                'fields' => json_encode(['nama_mempelai_pria','nama_mempelai_wanita','nama_ayah_pria','nama_ibu_pria','nama_ayah_wanita','nama_ibu_wanita','tanggal_akad','waktu_akad','lokasi_akad','tanggal_resepsi','waktu_resepsi','lokasi_resepsi']),
            ],
            [
                'slug' => 'surat-izin-keramaian',
                'name' => 'Surat Izin Keramaian',
                'group' => 'Legal & Administratif',
                'icon' => '🎉',
                'description' => 'Permohonan izin keramaian ke pihak berwenang',
                'color' => '#D97706',
                'templates' => json_encode(['Izin Hajatan', 'Izin Event']),
                'fields' => json_encode(['nama_penyelenggara','alamat','nama_kegiatan','tanggal','waktu','lokasi','perkiraan_peserta','kepada_ditujukan','kota','ttd']),
            ],

            // === KESEHATAN ===
            [
                'slug' => 'surat-sakit',
                'name' => 'Surat Keterangan Sakit',
                'group' => 'Kesehatan',
                'icon' => '🏥',
                'description' => 'Surat keterangan sakit dari dokter atau klinik',
                'color' => '#16A34A',
                'templates' => json_encode(['Surat Dokter', 'Surat Klinik']),
                'fields' => json_encode(['nama_pasien','tanggal_lahir','jenis_kelamin','alamat','diagnosis','istirahat_mulai','istirahat_selesai','nama_dokter','no_str','nama_fasilitas','kota','tanggal']),
            ],
            [
                'slug' => 'resume-medis',
                'name' => 'Resume Medis',
                'group' => 'Kesehatan',
                'icon' => '💊',
                'description' => 'Ringkasan riwayat medis pasien',
                'color' => '#0891B2',
                'templates' => json_encode(['Resume Rawat Inap', 'Resume Rawat Jalan']),
                'fields' => json_encode(['nama_pasien','no_rekam_medis','tanggal_lahir','alamat','tanggal_masuk','tanggal_keluar','diagnosa_masuk','diagnosa_keluar','tindakan','obat_pulang','nama_dokter','anjuran']),
            ],

            // === PROPERTI & SEWA ===
            [
                'slug' => 'surat-sewa-menyewa',
                'name' => 'Surat Perjanjian Sewa Menyewa',
                'group' => 'Properti & Sewa',
                'icon' => '🏘️',
                'description' => 'Kontrak sewa rumah, kos, ruko, atau properti lain',
                'color' => '#DC2626',
                'templates' => json_encode(['Sewa Rumah', 'Sewa Kos']),
                'fields' => json_encode(['nama_pemilik','nik_pemilik','alamat_pemilik','nama_penyewa','nik_penyewa','alamat_penyewa','alamat_objek_sewa','harga_sewa','periode_sewa','tanggal_mulai','tanggal_berakhir','syarat_ketentuan','kota','tanggal']),
            ],
            [
                'slug' => 'surat-jual-beli',
                'name' => 'Surat Jual Beli',
                'group' => 'Properti & Sewa',
                'icon' => '🔑',
                'description' => 'Surat perjanjian jual beli barang atau properti',
                'color' => '#7C3AED',
                'templates' => json_encode(['Jual Beli Kendaraan', 'Jual Beli Properti']),
                'fields' => json_encode(['nama_penjual','nik_penjual','nama_pembeli','nik_pembeli','objek_jual_beli','deskripsi','harga','cara_pembayaran','serah_terima','pernyataan_bebas_sengketa','saksi','kota','tanggal']),
            ],
            [
                'slug' => 'surat-serah-terima',
                'name' => 'Berita Acara Serah Terima',
                'group' => 'Properti & Sewa',
                'icon' => '📋',
                'description' => 'Berita acara penyerahan barang, dokumen, atau aset',
                'color' => '#0D9488',
                'templates' => json_encode(['Serah Terima Barang', 'Serah Terima Jabatan']),
                'fields' => json_encode(['nama_penyerah','jabatan_penyerah','nama_penerima','jabatan_penerima','daftar_item','kondisi','keterangan','saksi','kota','tanggal']),
            ],

            // === ORGANISASI & KOMUNITAS ===
            [
                'slug' => 'surat-undangan-rapat',
                'name' => 'Surat Undangan Rapat',
                'group' => 'Organisasi & Komunitas',
                'icon' => '📅',
                'description' => 'Undangan rapat resmi organisasi atau perusahaan',
                'color' => '#2563EB',
                'templates' => json_encode(['Undangan Formal', 'Undangan Internal']),
                'fields' => json_encode(['nama_organisasi','logo','nomor_surat','tanggal_surat','kepada','perihal','hari_tanggal','waktu','tempat','agenda','nama_pengirim','jabatan_pengirim']),
            ],
            [
                'slug' => 'surat-keputusan',
                'name' => 'Surat Keputusan (SK)',
                'group' => 'Organisasi & Komunitas',
                'icon' => '📜',
                'description' => 'Surat keputusan pengangkatan, pemberhentian, atau penetapan',
                'color' => '#DC2626',
                'templates' => json_encode(['SK Pengangkatan', 'SK Penetapan']),
                'fields' => json_encode(['nomor_sk','nama_organisasi','logo','tentang','menimbang','mengingat','memutuskan','menetapkan','masa_berlaku','kota','tanggal','nama_pimpinan','jabatan_pimpinan']),
            ],
            [
                'slug' => 'laporan-kegiatan',
                'name' => 'Laporan Kegiatan',
                'group' => 'Organisasi & Komunitas',
                'icon' => '📊',
                'description' => 'Laporan pelaksanaan kegiatan atau acara',
                'color' => '#D97706',
                'templates' => json_encode(['Laporan Event', 'Laporan Program']),
                'fields' => json_encode(['nama_kegiatan','nama_organisasi','tanggal','lokasi','peserta','tujuan','susunan_acara','hasil','hambatan','rekomendasi','dokumentasi','penutup','nama_pelapor']),
            ],
            [
                'slug' => 'proposal-kegiatan',
                'name' => 'Proposal Kegiatan',
                'group' => 'Organisasi & Komunitas',
                'icon' => '📝',
                'description' => 'Proposal acara, event, atau program kegiatan',
                'color' => '#16A34A',
                'templates' => json_encode(['Proposal Event', 'Proposal Sponsorship']),
                'fields' => json_encode(['nama_kegiatan','tema','logo','nama_organisasi','latar_belakang','tujuan','sasaran','waktu_pelaksanaan','tempat','susunan_acara','anggaran','susunan_panitia','penutup']),
            ],
            [
                'slug' => 'surat-permohonan-donasi',
                'name' => 'Surat Permohonan Donasi / Sponsor',
                'group' => 'Organisasi & Komunitas',
                'icon' => '🤲',
                'description' => 'Surat permohonan bantuan dana atau sponsorship',
                'color' => '#7C3AED',
                'templates' => json_encode(['Permohonan Donasi', 'Proposal Sponsor']),
                'fields' => json_encode(['nama_organisasi','logo','tujuan_kegiatan','nama_donatur_target','nominal_diharapkan','kegunaan_dana','kontak','rekening','nama_ketua','ttd']),
            ],

            // === PERSONAL & SOSIAL ===
            [
                'slug' => 'surat-cinta',
                'name' => 'Surat Cinta / Personal',
                'group' => 'Personal & Sosial',
                'icon' => '💌',
                'description' => 'Surat pribadi untuk orang tersayang',
                'color' => '#BE185D',
                'templates' => json_encode(['Surat Cinta Romantis', 'Surat untuk Sahabat']),
                'fields' => json_encode(['nama_penulis','nama_penerima','tanggal','isi_surat','kalimat_penutup','ttd']),
            ],
            [
                'slug' => 'surat-permohonan-maaf',
                'name' => 'Surat Permohonan Maaf',
                'group' => 'Personal & Sosial',
                'icon' => '🙏',
                'description' => 'Surat permintaan maaf formal atau personal',
                'color' => '#0891B2',
                'templates' => json_encode(['Maaf Formal', 'Maaf Personal']),
                'fields' => json_encode(['nama_pengirim','nama_penerima','kesalahan_yang_dilakukan','penyesalan','janji_perbaikan','tanggal','ttd']),
            ],
            [
                'slug' => 'ucapan-selamat',
                'name' => 'Surat / Kartu Ucapan',
                'group' => 'Personal & Sosial',
                'icon' => '🎊',
                'description' => 'Ucapan selamat untuk wisuda, ulang tahun, pernikahan, dll',
                'color' => '#D97706',
                'templates' => json_encode(['Ucapan Wisuda', 'Ucapan Ulang Tahun']),
                'fields' => json_encode(['nama_pengirim','nama_penerima','jenis_ucapan','pesan_utama','harapan','nama_penandatangan']),
            ],
            [
                'slug' => 'surat-izin-orang-tua',
                'name' => 'Surat Izin Orang Tua',
                'group' => 'Personal & Sosial',
                'icon' => '👨‍👩‍👧',
                'description' => 'Surat izin dari orang tua untuk kegiatan anak',
                'color' => '#16A34A',
                'templates' => json_encode(['Izin Kegiatan Sekolah', 'Izin Kegiatan Luar']),
                'fields' => json_encode(['nama_orang_tua','nama_anak','kelas','nama_kegiatan','tanggal_kegiatan','lokasi','keterangan','nama_sekolah','kota','tanggal_surat']),
            ],

            // === PERJALANAN & AKOMODASI ===
            [
                'slug' => 'surat-tugas',
                'name' => 'Surat Tugas / Perintah Jalan',
                'group' => 'Perjalanan & Akomodasi',
                'icon' => '✈️',
                'description' => 'Surat tugas dinas atau perintah perjalanan',
                'color' => '#2563EB',
                'templates' => json_encode(['Surat Tugas', 'SPPD']),
                'fields' => json_encode(['nomor_surat','nama_pegawai','jabatan','nip','nama_instansi','tujuan_kota','keperluan','tanggal_berangkat','tanggal_kembali','biaya','nama_pimpinan','jabatan_pimpinan']),
            ],
            [
                'slug' => 'itinerary',
                'name' => 'Itinerary Perjalanan',
                'group' => 'Perjalanan & Akomodasi',
                'icon' => '🗺️',
                'description' => 'Rencana perjalanan wisata atau dinas',
                'color' => '#0D9488',
                'templates' => json_encode(['Itinerary Wisata', 'Itinerary Bulan Madu']),
                'fields' => json_encode(['nama_wisatawan','tujuan','tanggal_keberangkatan','tanggal_kepulangan','jadwal_harian','akomodasi','transportasi','estimasi_biaya','catatan']),
            ],

            // === TEKNOLOGI & FREELANCE ===
            [
                'slug' => 'proposal-proyek-it',
                'name' => 'Proposal Proyek IT / Freelance',
                'group' => 'Teknologi & Freelance',
                'icon' => '💻',
                'description' => 'Proposal pengerjaan proyek website, aplikasi, atau digital',
                'color' => '#7C3AED',
                'templates' => json_encode(['Proposal Web Dev', 'Proposal Design']),
                'fields' => json_encode(['nama_freelancer','portofolio_link','nama_klien','nama_proyek','deskripsi_proyek','teknologi','scope_pekerjaan','timeline','harga','syarat_pembayaran','garansi','ttd']),
            ],
            [
                'slug' => 'nda',
                'name' => 'NDA / Perjanjian Kerahasiaan',
                'group' => 'Teknologi & Freelance',
                'icon' => '🔒',
                'description' => 'Non-Disclosure Agreement untuk melindungi informasi rahasia',
                'color' => '#DC2626',
                'templates' => json_encode(['NDA Unilateral', 'NDA Mutual']),
                'fields' => json_encode(['pihak_pengungkap','pihak_penerima','definisi_informasi_rahasia','kewajiban_kerahasiaan','pengecualian','jangka_waktu','konsekuensi_pelanggaran','hukum_yang_berlaku','kota','tanggal']),
            ],
            [
                'slug' => 'deskripsi-produk',
                'name' => 'Deskripsi Produk / Katalog',
                'group' => 'Teknologi & Freelance',
                'icon' => '🛍️',
                'description' => 'Dokumen deskripsi produk atau katalog untuk pemasaran',
                'color' => '#D97706',
                'templates' => json_encode(['Katalog Produk', 'Product Sheet']),
                'fields' => json_encode(['nama_produk','foto_produk','kategori','deskripsi_singkat','spesifikasi','keunggulan','harga','cara_pemesanan','kontak','nama_brand']),
            ],

            // === PEMERINTAHAN & INSTANSI ===
            [
                'slug' => 'surat-resmi-dinas',
                'name' => 'Surat Resmi Dinas / Instansi',
                'group' => 'Pemerintahan & Instansi',
                'icon' => '🏛️',
                'description' => 'Surat resmi format pemerintahan atau instansi',
                'color' => '#0891B2',
                'templates' => json_encode(['Format Surat Dinas', 'Surat Edaran']),
                'fields' => json_encode(['nama_instansi','logo','alamat_instansi','nomor_surat','tanggal','klasifikasi','kepada','perihal','isi_surat','nama_penandatangan','jabatan','nip']),
            ],
            [
                'slug' => 'surat-pengaduan',
                'name' => 'Surat Pengaduan / Komplain',
                'group' => 'Pemerintahan & Instansi',
                'icon' => '📢',
                'description' => 'Surat pengaduan resmi kepada instansi atau perusahaan',
                'color' => '#DC2626',
                'templates' => json_encode(['Pengaduan Publik', 'Komplain Layanan']),
                'fields' => json_encode(['nama_pengadu','nik','alamat','no_hp','kepada','perihal','kronologi','bukti','tuntutan','kota','tanggal','ttd']),
            ],
            [
                'slug' => 'surat-permohonan-beasiswa',
                'name' => 'Surat Permohonan Beasiswa',
                'group' => 'Pemerintahan & Instansi',
                'icon' => '🎓',
                'description' => 'Surat permohonan bantuan beasiswa pendidikan',
                'color' => '#16A34A',
                'templates' => json_encode(['Beasiswa KIP', 'Beasiswa Perusahaan']),
                'fields' => json_encode(['nama','nim','program_studi','kampus','ipk','semester','kondisi_ekonomi','prestasi','tujuan','kepada','nama_orang_tua','penghasilan_ortu','ttd']),
            ],
        ];

        foreach ($categories as $category) {
            DB::table('document_categories')->updateOrInsert(
                ['slug' => $category['slug']],
                array_merge($category, [
                    'is_active' => true,
                    'sort_order' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }
}
